# https://docs.docker.com/compose/compose-file
# written for development expirementation -
version: '3'
services:
  web:
    restart: "no"
    build: . # build an image using the ./Dockerfile
    depends_on:
      - redis
    ports:
      - "5000:5000"
    expose:
      - "5000"
    command: ["flask", "run", "--host=0.0.0.0"]


  worker:
    restart: "no"
    build: . # build an image using the ./Dockerfile
    depends_on:
      - redis
    command: ['rq', 'worker' ,'--with-scheduler', '-u','redis://redis:6379']

  redis:
   image: redis
   restart: "no"
   ports:
     - "6379:6379"
#################################
# Add redis container
#################################
